FORMAT: 1A
HOST: http://localhost:8000/

# Jwt API

#Laravel Server

## Register User [/api/register]

### Register User[POST]

Validation Rule for this endpoint are :

name : required|string|max:255
username : required|string|min:6|max:20|unique:users
password : required|string|min:6
role : required|string

+ Request (application/form-data)

        {
            "name": "name",
            "username": "username",
            "password": "password",
            "role": "role",
        }

+ Response 200 (application/json)

        {
            "message": "Register Berhasil"
        }
        
+ Response 400 (application/json)

        {
            "message": "Register Gagal"
        }

## Login User [/api/login]

### Login User [POST]

Validation Rule for this endpoint are :

username : required|string|min:6|max:20
password : required|string|min:6

+ Request (application/form-data)

        {
            "username": "username",
            "password": "password",
        }

+ Response 200 (application/json)

        {
            "response": "success",
            "result": {
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6ImZMUGg1WTZSNW1pVVU3cEEifQ.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMCIsInN1YiI6IjIiLCJqdGkiOiJmTFBoNVk2UjVtaVVVN3BBIiwiaWF0IjoxNTA5MjU2MTg1LCJuYmYiOjE1MDkyNTYxODUsImV4cCI6MTUwOTI1OTc4NSwicmxpIjoxNTA5NjkxNzg1LCJuYW1lIjoiaWtoc2FuIiwidXNlcm5hbWUiOiJpa2hzYW4yIiwicm9sZSI6ImlraHNhbiIsInRpbWVzdGFtcCI6IjIwMTctMTAtMjkgMDU6NDk6NDUifQ.9A8Od-_lA3a2H2OLM7aspsPWqZwLe6RKpPy9s2Awdcw"
            }
        }

+ Response 400 (application/json)

        {
            "message": "Invalid Credential"
        }

## Decode Token [/api/decode]

### Decode Token [POST]

Validation Rule for this endpoint are :

token : required

+ Request (application/form-data)

        {
            "token": "token",
        }

+ Response 200 (application/json)

        {
            "iss": "http://localhost:8000",
            "sub": "2",
            "jti": "z4iSXdvAmrboEUBz",
            "iat": 1509208072,
            "nbf": 1509208072,
            "exp": 1509211672,
            "rli": 1509643672,
            "name": "ikhsan",
            "username": "ikhsan2",
            "role": "ikhsan",
            "timestamp": "2017-10-28 16:27:52"
        }
        
+ Response 400 (application/json)

        {
            "message": "Invalid Token"
        }

## NodeJS Backend PORT:3000 [/{token}]

Please note this API use different host from Laravel backend usually laravel dev server run on `localhost:8000` and express run on `localhost:3000`

### Decode Token [POST]

+ Parameters
    + token (string) - token

+ Response 200 (application/json)

        {
            "iss": "http://localhost:8000",
            "sub": "2",
            "jti": "z4iSXdvAmrboEUBz",
            "iat": 1509208072,
            "nbf": 1509208072,
            "exp": 1509211672,
            "rli": 1509643672,
            "name": "ikhsan",
            "username": "ikhsan2",
            "role": "ikhsan",
            "timestamp": "2017-10-28 16:27:52"
        }